Repository JihyeChu/PetNexus, pull requests merged in 2023-09, with the labels that each got.

#36 Create README.md
  README.md
Labels: documentation

#38 [Feat] Front Trade + Post
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomController.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomViewController.java
  src/main/java/com/sparta/petnexus/post/controller/PostController.java
  src/main/java/com/sparta/petnexus/post/dto/PostResponseDto.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeController.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeViewController.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeResponseDto.java
  src/main/java/com/sparta/petnexus/trade/entity/Trade.java
  src/main/resources/static/header.html
  src/main/resources/templates/community.html
  src/main/resources/templates/createChat.html
  src/main/resources/templates/createPost.html
  src/main/resources/templates/createTrade.html
  src/main/resources/templates/home.html
  src/main/resources/templates/hospital.html
  src/main/resources/templates/openChat.html
  src/main/resources/templates/post.html
  src/main/resources/templates/trade.html
  src/main/resources/templates/tradeMarket.html
Labels: front

#41 [Feat] docker 세팅 파일 추가 및 수정
  Dockerfile
  build.gradle
  src/main/resources/application.properties
Labels: enhancement

#39 [Feat] Post, Trade 페이지네이션 + 검색기능(페이징)
  src/main/java/com/sparta/petnexus/post/controller/PostController.java
  src/main/java/com/sparta/petnexus/post/controller/PostViewController.java
  src/main/java/com/sparta/petnexus/post/dto/PostResponseDto.java
  src/main/java/com/sparta/petnexus/post/repository/PostRepository.java
  src/main/java/com/sparta/petnexus/post/service/PostService.java
  src/main/java/com/sparta/petnexus/post/service/PostServiceImpl.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeController.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeViewController.java
  src/main/java/com/sparta/petnexus/trade/repository/TradeRepository.java
  src/main/java/com/sparta/petnexus/trade/service/TradeService.java
  src/main/java/com/sparta/petnexus/trade/service/TradeServiceImpl.java
  src/main/resources/templates/community.html
  src/main/resources/templates/tradeMarket.html
Labels: enhancement, front

#42 [Refactor] Post/Trade 리팩토링
  src/main/java/com/sparta/petnexus/post/controller/PostController.java
  src/main/java/com/sparta/petnexus/post/controller/PostViewController.java
  src/main/java/com/sparta/petnexus/post/repository/PostRepository.java
  src/main/java/com/sparta/petnexus/post/service/PostService.java
  src/main/java/com/sparta/petnexus/post/service/PostServiceImpl.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeController.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeViewController.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeRequestDto.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeResponseDto.java
  src/main/java/com/sparta/petnexus/trade/entity/Trade.java
  src/main/java/com/sparta/petnexus/trade/repository/TradeRepository.java
  src/main/java/com/sparta/petnexus/trade/service/TradeService.java
  src/main/java/com/sparta/petnexus/trade/service/TradeServiceImpl.java
  src/main/resources/templates/community.html
  src/main/resources/templates/tradeMarket.html
Labels: refactoring

#44 [Refactor] front page, search
  src/main/java/com/sparta/petnexus/post/controller/PostViewController.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeViewController.java
  src/main/resources/templates/community.html
  src/main/resources/templates/tradeMarket.html
Labels: front

#54 [Fix] stomp 인터셉터 fix
  src/main/java/com/sparta/petnexus/chat/StompHandler.java
  src/main/java/com/sparta/petnexus/chat/config/StompWebSocketConfig.java
  src/main/java/com/sparta/petnexus/common/security/jwt/TokenProvider.java
  src/main/resources/templates/openChatRoom.html
  src/main/resources/templates/tradeChatRoom.html
Labels: fix

#82 [fix] Redis fix
  src/main/java/com/sparta/petnexus/common/security/jwt/TokenProvider.java
Labels: fix

#84 [Refactor] 웹소켓 연결 도메인 수정
  src/main/resources/templates/openChatRoom.html
Labels: refactoring

#88 [Refactor] Redis PUB/SUB 로 채팅 기능 개선
  src/main/java/com/sparta/petnexus/Image/entity/Image.java
  src/main/java/com/sparta/petnexus/Image/repository/ImageRepository.java
  src/main/java/com/sparta/petnexus/chat/StompHandler.java
  src/main/java/com/sparta/petnexus/chat/config/StompWebSocketConfig.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatController.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomController.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomViewController.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatMessageDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatResponseDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRoomRequestDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/sparta/petnexus/chat/entity/Chat.java
  src/main/java/com/sparta/petnexus/chat/entity/ChatRoom.java
  src/main/java/com/sparta/petnexus/chat/entity/ChatType.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRepository.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRoomRedisRepository.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRoomRepository.java
  src/main/java/com/sparta/petnexus/chat/service/ChatRoomService.java
  src/main/java/com/sparta/petnexus/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/sparta/petnexus/chat/service/ChatService.java
  src/main/java/com/sparta/petnexus/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/petnexus/common/redis/config/RedisConfig.java
  src/main/java/com/sparta/petnexus/common/redis/pubsub/RedisPublisher.java
  src/main/java/com/sparta/petnexus/common/redis/pubsub/RedisSubscriber.java
Labels: refactoring

#92 [fix] redis
  .github/workflows/CI-CD.yml
  src/main/java/com/sparta/petnexus/Image/entity/Image.java
  src/main/java/com/sparta/petnexus/Image/repository/ImageRepository.java
  src/main/java/com/sparta/petnexus/chat/StompHandler.java
  src/main/java/com/sparta/petnexus/chat/config/StompWebSocketConfig.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatController.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomController.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomViewController.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatListResponseDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatMessageDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatResponseDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRoomRequestDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/sparta/petnexus/chat/entity/Chat.java
  src/main/java/com/sparta/petnexus/chat/entity/ChatRoom.java
  src/main/java/com/sparta/petnexus/chat/entity/ChatType.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRepository.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRoomRedisRepository.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRoomRepository.java
  src/main/java/com/sparta/petnexus/chat/service/ChatRoomService.java
  src/main/java/com/sparta/petnexus/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/sparta/petnexus/chat/service/ChatService.java
  src/main/java/com/sparta/petnexus/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/petnexus/common/redis/config/RedisConfig.java
  src/main/java/com/sparta/petnexus/common/redis/pubsub/RedisPublisher.java
  src/main/java/com/sparta/petnexus/common/redis/pubsub/RedisSubscriber.java
  src/main/resources/templates/openChatRoom.html
  src/main/resources/templates/tradeChatRoom.html
Labels: fix

#102 [bug] chat_chk_1
  src/main/java/com/sparta/petnexus/chat/entity/Chat.java
Labels: bug

#107 [Fix] chat read to repo
  src/main/java/com/sparta/petnexus/chat/service/ChatServiceImpl.java
Labels: fix

#108 [fix] chat read to repo
  src/main/java/com/sparta/petnexus/chat/service/ChatServiceImpl.java
Labels: fix

#110 [Refactor] 채팅 기능 원복
  src/main/java/com/sparta/petnexus/Image/repository/ImageRepository.java
  src/main/java/com/sparta/petnexus/chat/StompHandler.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatController.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomController.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomViewController.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatMessageDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatResponseDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRoomRequestDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/sparta/petnexus/chat/entity/Chat.java
  src/main/java/com/sparta/petnexus/chat/entity/ChatRoom.java
  src/main/java/com/sparta/petnexus/chat/entity/ChatType.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRepository.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRoomRedisRepository.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRoomRepository.java
  src/main/java/com/sparta/petnexus/chat/service/ChatRoomService.java
  src/main/java/com/sparta/petnexus/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/sparta/petnexus/chat/service/ChatService.java
  src/main/java/com/sparta/petnexus/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/petnexus/common/redis/config/RedisConfig.java
  src/main/java/com/sparta/petnexus/common/redis/pubsub/RedisPublisher.java
  src/main/java/com/sparta/petnexus/common/redis/pubsub/RedisSubscriber.java
Labels: refactoring

#111 [Refactor] 오픈채팅 프론트
  src/main/java/com/sparta/petnexus/chat/controller/ChatController.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomViewController.java
  src/main/resources/static/css/main.css
  src/main/resources/static/css/openChatRoom.css
  src/main/resources/static/img/back01.jpg
  src/main/resources/static/img/profile01.jpg
  src/main/resources/templates/openChatRoom.html
Labels: refactoring, front

#114 Update README.md
  README.md
Labels: documentation

#113 [Refactor] login, signup, chat front
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomViewController.java
  src/main/java/com/sparta/petnexus/common/security/config/securityConfig.java
  src/main/java/com/sparta/petnexus/user/controller/UserViewController.java
  src/main/resources/static/css/chatRoom.css
  src/main/resources/static/css/login.css
  src/main/resources/static/img/back01.jpeg
  src/main/resources/templates/header.html
  src/main/resources/templates/login.html
  src/main/resources/templates/oauthLogin.html
  src/main/resources/templates/openChatRoom.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/tradeChatRoom.html
Labels: front

#116 Update README.md
  README.md
Labels: documentation

#117 [Refactor] trade - price 금액 표시 방법 수정
  src/main/java/com/sparta/petnexus/trade/dto/TradeResponseDto.java
Labels: refactoring

#122 Update README.md
  README.md
Labels: documentation

#124 [Refactor] Trade 카테고리별 조회(Front)
  src/main/resources/templates/tradeMarket.html
Labels: front

#126 Update README.md
  README.md
Labels: documentation
