Repository JihyeChu/PetNexus, pull requests merged in 2023-08, with the labels that each got.

#2 [Feat] 유저 회원가입 구현
  build.gradle
  src/main/java/com/sparta/petnexus/PetNexusApplication.java
  src/main/java/com/sparta/petnexus/common/config/PasswordEncode.java
  src/main/java/com/sparta/petnexus/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/petnexus/user/controller/UserController.java
  src/main/java/com/sparta/petnexus/user/dto/SignUpUserRequest.java
  src/main/java/com/sparta/petnexus/user/entity/User.java
  src/main/java/com/sparta/petnexus/user/repository/UserRepository.java
  src/main/java/com/sparta/petnexus/user/service/UserService.java
Labels: enhancement

#3 [Feat] Post CRUD 구현
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/post/controller/PostController.java
  src/main/java/com/sparta/petnexus/post/dto/PostRequestDto.java
  src/main/java/com/sparta/petnexus/post/dto/PostResponseDto.java
  src/main/java/com/sparta/petnexus/post/entity/Post.java
  src/main/java/com/sparta/petnexus/post/repository/PostRepository.java
  src/main/java/com/sparta/petnexus/post/service/PostService.java
Labels: enhancement

#4 [Feat] Trade CRUD 구현
  CONVENTION.md
  build.gradle
  src/main/java/com/sparta/petnexus/trade/controller/TradeController.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeRequestDto.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeResponseDto.java
  src/main/java/com/sparta/petnexus/trade/entity/CategoryEnum.java
  src/main/java/com/sparta/petnexus/trade/entity/Trade.java
  src/main/java/com/sparta/petnexus/trade/repository/TradeRepository.java
  src/main/java/com/sparta/petnexus/trade/service/TradeService.java
Labels: feature

#6 post Refactor
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/post/controller/PostController.java
  src/main/java/com/sparta/petnexus/post/dto/PostRequestDto.java
  src/main/java/com/sparta/petnexus/post/service/PostService.java
Labels: feature

#7 [Feat] 유저 일반 로그인 구현
  build.gradle
  src/main/java/com/sparta/petnexus/PetNexusApplication.java
  src/main/java/com/sparta/petnexus/common/config/PasswordEncode.java
  src/main/java/com/sparta/petnexus/common/security/config/securityConfig.java
  src/main/java/com/sparta/petnexus/common/security/entity/UserDetailServiceImp.java
  src/main/java/com/sparta/petnexus/common/security/entity/UserDetailsImpl.java
  src/main/java/com/sparta/petnexus/common/security/filter/TokenAuthenticationFilter.java
  src/main/java/com/sparta/petnexus/common/security/jwt/JwtProperties.java
  src/main/java/com/sparta/petnexus/common/security/jwt/TokenProvider.java
  src/main/java/com/sparta/petnexus/user/controller/UserController.java
  src/main/java/com/sparta/petnexus/user/dto/LoginRequest.java
  src/main/java/com/sparta/petnexus/user/dto/SignupRequest.java
  src/main/java/com/sparta/petnexus/user/entity/User.java
  src/main/java/com/sparta/petnexus/user/entity/UserRoleEnum.java
  src/main/java/com/sparta/petnexus/user/repository/UserRepository.java
  src/main/java/com/sparta/petnexus/user/service/UserService.java
  src/main/resources/application.yml
Labels: feature

#9 [Refactor] trade crud
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeController.java
  src/main/java/com/sparta/petnexus/trade/entity/Trade.java
  src/main/java/com/sparta/petnexus/trade/service/TradeService.java
Labels: refactoring

#8 [Refactor]post curd 개선 및 login 정보 확인 추가
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/post/controller/PostController.java
  src/main/java/com/sparta/petnexus/post/dto/PostRequestDto.java
  src/main/java/com/sparta/petnexus/post/dto/PostResponseDto.java
  src/main/java/com/sparta/petnexus/post/entity/Post.java
  src/main/java/com/sparta/petnexus/post/service/PostService.java
Labels: refactoring

#11 [Feat] Trade like + bookmark
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/trade/bookmark/entity/TradeBookmark.java
  src/main/java/com/sparta/petnexus/trade/bookmark/repository/TradeBookmarkRepository.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeController.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeRequestDto.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeResponseDto.java
  src/main/java/com/sparta/petnexus/trade/entity/Trade.java
  src/main/java/com/sparta/petnexus/trade/like/entity/TradeLike.java
  src/main/java/com/sparta/petnexus/trade/like/repository/TradeLikeRepository.java
  src/main/java/com/sparta/petnexus/trade/repository/TradeRepository.java
  src/main/java/com/sparta/petnexus/trade/service/TradeService.java
  src/main/java/com/sparta/petnexus/trade/service/TradeServiceImpl.java
Labels: feature

#12 [Feat] PostLike + PostComment + post comment 조회
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/post/controller/PostController.java
  src/main/java/com/sparta/petnexus/post/dto/PostResponseDto.java
  src/main/java/com/sparta/petnexus/post/entity/Post.java
  src/main/java/com/sparta/petnexus/post/postBookmark/entity/PostBookmark.java
  src/main/java/com/sparta/petnexus/post/postBookmark/repository/PostBookmarkRepository.java
  src/main/java/com/sparta/petnexus/post/postComment/controller/PostCommentController.java
  src/main/java/com/sparta/petnexus/post/postComment/dto/PostCommentRequestsDto.java
  src/main/java/com/sparta/petnexus/post/postComment/dto/PostCommentResponseDto.java
  src/main/java/com/sparta/petnexus/post/postComment/entity/PostComment.java
  src/main/java/com/sparta/petnexus/post/postComment/repository/PostCommentRepository.java
  src/main/java/com/sparta/petnexus/post/postComment/service/PostCommentService.java
  src/main/java/com/sparta/petnexus/post/postComment/service/PostCommentServiceImpl.java
  src/main/java/com/sparta/petnexus/post/postLike/entity/PostLike.java
  src/main/java/com/sparta/petnexus/post/postLike/repository/PostLikeRepository.java
  src/main/java/com/sparta/petnexus/post/service/PostService.java
  src/main/java/com/sparta/petnexus/post/service/PostServiceImpl.java
Labels: enhancement

#13 [Feat] 1:1 채팅 기능 구현
  build.gradle
  src/main/java/com/sparta/petnexus/PetNexusApplication.java
  src/main/java/com/sparta/petnexus/chat/config/StompWebSocketConfig.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatController.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatListResponseDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRequestDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatResponseDto.java
  src/main/java/com/sparta/petnexus/chat/entity/Chat.java
  src/main/java/com/sparta/petnexus/chat/entity/Timestamped.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRepository.java
  src/main/java/com/sparta/petnexus/chat/service/ChatService.java
  src/main/java/com/sparta/petnexus/chat/service/ChatServiceImpl.java
Labels: enhancement

#14 [Feat] PostBookmark + like, comment 메서드 수정
  src/main/java/com/sparta/petnexus/post/postLike/entity/PostLike.java
Labels: enhancement

#17 [Feat] trade comment + like
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/trade/comment/controller/TradeCommentController.java
  src/main/java/com/sparta/petnexus/trade/comment/dto/TradeCommentRequestDto.java
  src/main/java/com/sparta/petnexus/trade/comment/dto/TradeCommentResponseDto.java
  src/main/java/com/sparta/petnexus/trade/comment/entity/TradeComment.java
  src/main/java/com/sparta/petnexus/trade/comment/repository/TradeCommentRepository.java
  src/main/java/com/sparta/petnexus/trade/comment/service/TradeCommentService.java
  src/main/java/com/sparta/petnexus/trade/comment/service/TradeCommentServiceImpl.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeController.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeResponseDto.java
  src/main/java/com/sparta/petnexus/trade/entity/Trade.java
  src/main/java/com/sparta/petnexus/trade/service/TradeServiceImpl.java
Labels: feature, refactoring

#16 [Feat] Swagger 추가(JWT 인증 버튼 셋업)
  build.gradle
  src/main/java/com/sparta/petnexus/chat/controller/ChatController.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatResponseDto.java
  src/main/java/com/sparta/petnexus/common/security/config/SwaggerConfig.java
  src/main/java/com/sparta/petnexus/common/security/config/securityConfig.java
Labels: enhancement, feature

#15 [Feat] RefreshToken Redis Save and Oauth2 Login
  .gitignore
  build.gradle
  src/main/java/com/sparta/petnexus/common/redis/config/RedisConfig.java
  src/main/java/com/sparta/petnexus/common/redis/utils/RedisUtils.java
  src/main/java/com/sparta/petnexus/common/security/config/securityConfig.java
  src/main/java/com/sparta/petnexus/common/security/entity/UserDetailsImpl.java
  src/main/java/com/sparta/petnexus/common/security/filter/TokenAuthenticationFilter.java
  src/main/java/com/sparta/petnexus/common/security/info/OAuth2UserInfo.java
  src/main/java/com/sparta/petnexus/common/security/info/OAuth2UserInfoFactory.java
  src/main/java/com/sparta/petnexus/common/security/info/ProviderType.java
  src/main/java/com/sparta/petnexus/common/security/info/impl/FacebookOAuth2UserInfo.java
  src/main/java/com/sparta/petnexus/common/security/info/impl/GoogleOAuth2UserInfo.java
  src/main/java/com/sparta/petnexus/common/security/info/impl/KakaoOAuth2UserInfo.java
  src/main/java/com/sparta/petnexus/common/security/info/impl/NaverOAuth2UserInfo.java
  src/main/java/com/sparta/petnexus/common/security/jwt/TokenProvider.java
  src/main/java/com/sparta/petnexus/common/security/oauth/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/sparta/petnexus/common/security/oauth/OAuth2SuccessHandler.java
  src/main/java/com/sparta/petnexus/common/security/oauth/OAuth2UserCustomService.java
  src/main/java/com/sparta/petnexus/common/security/properties/AppProperties.java
  src/main/java/com/sparta/petnexus/common/security/properties/CorsProperties.java
  src/main/java/com/sparta/petnexus/common/util/CookieUtil.java
  src/main/java/com/sparta/petnexus/token/controller/TokenController.java
  src/main/java/com/sparta/petnexus/token/entity/RefreshToken.java
  src/main/java/com/sparta/petnexus/token/repository/RefreshTokenRepository.java
  src/main/java/com/sparta/petnexus/token/service/TokenService.java
  src/main/java/com/sparta/petnexus/user/controller/UserController.java
  src/main/java/com/sparta/petnexus/user/controller/UserViewController.java
  src/main/java/com/sparta/petnexus/user/dto/SignupRequest.java
  src/main/java/com/sparta/petnexus/user/entity/User.java
  src/main/java/com/sparta/petnexus/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/static/img/google.png
  src/main/resources/static/img/kakao.png
  src/main/resources/static/img/naver.png
  src/main/resources/templates/oauthLogin.html
Labels: enhancement, feature

#19 [Refactor] UserController Swagger 적용
  src/main/java/com/sparta/petnexus/common/config/SwaggerConfig.java
  src/main/java/com/sparta/petnexus/common/security/config/securityConfig.java
  src/main/java/com/sparta/petnexus/common/security/entity/UserDetailServiceImp.java
  src/main/java/com/sparta/petnexus/common/security/jwt/TokenProvider.java
  src/main/java/com/sparta/petnexus/common/security/oauth/OAuth2SuccessHandler.java
  src/main/java/com/sparta/petnexus/common/security/properties/AppProperties.java
  src/main/java/com/sparta/petnexus/user/controller/UserController.java
  src/main/java/com/sparta/petnexus/user/dto/LoginRequest.java
  src/main/java/com/sparta/petnexus/user/dto/SignupRequest.java
  src/main/java/com/sparta/petnexus/user/service/UserService.java
Labels: refactoring

#20 [Refactor] Post Swagger 적용
  src/main/java/com/sparta/petnexus/post/controller/PostController.java
  src/main/java/com/sparta/petnexus/post/dto/PostRequestDto.java
  src/main/java/com/sparta/petnexus/post/dto/PostResponseDto.java
  src/main/java/com/sparta/petnexus/post/postComment/controller/PostCommentController.java
  src/main/java/com/sparta/petnexus/post/postComment/dto/PostCommentRequestsDto.java
  src/main/java/com/sparta/petnexus/post/postComment/dto/PostCommentResponseDto.java
Labels: refactoring

#21 [Refactor] Trade Swagger 적용
  src/main/java/com/sparta/petnexus/trade/comment/controller/TradeCommentController.java
  src/main/java/com/sparta/petnexus/trade/comment/dto/TradeCommentRequestDto.java
  src/main/java/com/sparta/petnexus/trade/comment/dto/TradeCommentResponseDto.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeController.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeRequestDto.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeResponseDto.java
Labels: refactoring

#22 [Refactor] 채팅방 생성 및 Trade 연관관계 추가
  src/main/java/com/sparta/petnexus/chat/controller/ChatController.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomController.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatListResponseDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRequestDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatResponseDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRoomListResponseDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRoomRequestDto.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/sparta/petnexus/chat/dto/TradeChatRoomListResponseDto.java
  src/main/java/com/sparta/petnexus/chat/dto/TradeChatRoomResponseDto.java
  src/main/java/com/sparta/petnexus/chat/entity/Chat.java
  src/main/java/com/sparta/petnexus/chat/entity/ChatRoom.java
  src/main/java/com/sparta/petnexus/chat/entity/Timestamped.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRepository.java
  src/main/java/com/sparta/petnexus/chat/repository/ChatRoomRepository.java
  src/main/java/com/sparta/petnexus/chat/service/ChatRoomService.java
  src/main/java/com/sparta/petnexus/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/sparta/petnexus/chat/service/ChatService.java
  src/main/java/com/sparta/petnexus/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
Labels: refactoring

#25 [Feat] aws s3 파일 업로드 & 조회 기능 구현 + 코드 개선
  build.gradle
  src/main/java/com/sparta/petnexus/Image/config/AwsS3Config.java
  src/main/java/com/sparta/petnexus/Image/config/AwsS3upload.java
  src/main/java/com/sparta/petnexus/Image/entity/Image.java
  src/main/java/com/sparta/petnexus/Image/repository/ImageRepository.java
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/post/controller/PostController.java
  src/main/java/com/sparta/petnexus/post/entity/Post.java
  src/main/java/com/sparta/petnexus/post/postBookmark/entity/PostBookmark.java
  src/main/java/com/sparta/petnexus/post/postComment/controller/PostCommentController.java
  src/main/java/com/sparta/petnexus/post/postComment/entity/PostComment.java
  src/main/java/com/sparta/petnexus/post/postComment/service/PostCommentServiceImpl.java
  src/main/java/com/sparta/petnexus/post/postLike/entity/PostLike.java
  src/main/java/com/sparta/petnexus/post/service/PostService.java
  src/main/java/com/sparta/petnexus/post/service/PostServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement, refactoring

#26 [Feat] TradeMapApi, 코드 리팩토링
  src/main/java/com/sparta/petnexus/trade/comment/controller/TradeCommentController.java
  src/main/java/com/sparta/petnexus/trade/comment/service/TradeCommentServiceImpl.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeRequestDto.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeResponseDto.java
  src/main/java/com/sparta/petnexus/trade/entity/Trade.java
  src/main/java/com/sparta/petnexus/trade/service/TradeServiceImpl.java
  src/main/java/com/sparta/petnexus/user/controller/UserViewController.java
  src/main/resources/templates/tradeKakaoMap.html
Labels: enhancement, refactoring

#27 [Feat] Front init, Pet CRUD, logout
  src/main/java/com/sparta/petnexus/chat/config/StompWebSocketConfig.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatController.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomViewController.java
  src/main/java/com/sparta/petnexus/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/common/redis/utils/RedisUtils.java
  src/main/java/com/sparta/petnexus/common/security/config/securityConfig.java
  src/main/java/com/sparta/petnexus/common/security/jwt/TokenProvider.java
  src/main/java/com/sparta/petnexus/common/security/oauth/OAuth2SuccessHandler.java
  src/main/java/com/sparta/petnexus/post/controller/PostViewController.java
  src/main/java/com/sparta/petnexus/post/dto/PostResponseDto.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeViewController.java
  src/main/java/com/sparta/petnexus/trade/dto/TradeResponseDto.java
  src/main/java/com/sparta/petnexus/user/controller/UserController.java
  src/main/java/com/sparta/petnexus/user/controller/UserViewController.java
  src/main/java/com/sparta/petnexus/user/dto/AddPetRequest.java
  src/main/java/com/sparta/petnexus/user/dto/ProfileRequest.java
  src/main/java/com/sparta/petnexus/user/entity/User.java
  src/main/java/com/sparta/petnexus/user/pet/entity/Pet.java
  src/main/java/com/sparta/petnexus/user/pet/entity/PetGender.java
  src/main/java/com/sparta/petnexus/user/pet/entity/PetKind.java
  src/main/java/com/sparta/petnexus/user/pet/entity/PetType.java
  src/main/java/com/sparta/petnexus/user/pet/repository/PetRepository.java
  src/main/java/com/sparta/petnexus/user/service/UserService.java
  src/main/resources/static/css/main.css
  src/main/resources/static/js/article.js
  src/main/resources/static/js/hospital.js
  src/main/resources/static/js/soket.js
  src/main/resources/static/js/token.js
  src/main/resources/templates/community.html
  src/main/resources/templates/createPost.html
  src/main/resources/templates/home.html
  src/main/resources/templates/hospital.html
  src/main/resources/templates/oauthLogin.html
  src/main/resources/templates/openChat.html
  src/main/resources/templates/post.html
  src/main/resources/templates/trade.html
  src/main/resources/templates/websoket.html
Labels: feature

#28 [Refactor] createPost RequestPart으로 수정
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/post/controller/PostController.java
  src/main/java/com/sparta/petnexus/post/service/PostServiceImpl.java
Labels: enhancement

#29 [Feature] SSE를 통한 실시간 알림 기능 구현
  src/main/java/com/sparta/petnexus/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/notification/config/AsyncConfig.java
  src/main/java/com/sparta/petnexus/notification/controller/NotificationController.java
  src/main/java/com/sparta/petnexus/notification/dto/NotificationListResponseDto.java
  src/main/java/com/sparta/petnexus/notification/dto/NotificationRequestDto.java
  src/main/java/com/sparta/petnexus/notification/dto/NotificationResponseDto.java
  src/main/java/com/sparta/petnexus/notification/entity/Notification.java
  src/main/java/com/sparta/petnexus/notification/entity/NotificationType.java
  src/main/java/com/sparta/petnexus/notification/repository/EmitterRepository.java
  src/main/java/com/sparta/petnexus/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/sparta/petnexus/notification/repository/NotificationRepository.java
  src/main/java/com/sparta/petnexus/notification/service/NotificationService.java
  src/main/java/com/sparta/petnexus/notification/service/NotificationServiceImpl.java
  src/main/java/com/sparta/petnexus/post/postComment/service/PostCommentServiceImpl.java
  src/main/java/com/sparta/petnexus/post/service/PostServiceImpl.java
  src/main/java/com/sparta/petnexus/trade/comment/service/TradeCommentServiceImpl.java
  src/main/java/com/sparta/petnexus/trade/service/TradeServiceImpl.java
Labels: feature

#34 [Refactor] createPost RequestPart으로 수정
  src/main/java/com/sparta/petnexus/Image/entity/Image.java
  src/main/java/com/sparta/petnexus/chat/controller/ChatRoomController.java
  src/main/java/com/sparta/petnexus/chat/service/ChatRoomService.java
  src/main/java/com/sparta/petnexus/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/sparta/petnexus/common/exception/ErrorCode.java
  src/main/java/com/sparta/petnexus/post/controller/PostController.java
  src/main/java/com/sparta/petnexus/post/service/PostService.java
  src/main/java/com/sparta/petnexus/post/service/PostServiceImpl.java
  src/main/java/com/sparta/petnexus/trade/controller/TradeController.java
  src/main/java/com/sparta/petnexus/trade/service/TradeService.java
  src/main/java/com/sparta/petnexus/trade/service/TradeServiceImpl.java
Labels: refactoring
